### ISSUE TITLE
Task :react-native-config:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by Flavien** [react-native-config/react-native-config#330]
I get the following exception when building with `assembleRelease`. This is version 0.11.7 with react-native 0.58.3.

```
> Task :react-native-config:verifyReleaseResources FAILED
Shutdown finished in 0ms

:react-native-config:verifyReleaseResources (Thread[Task worker for ':',5,main]) completed. Took 3.026 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-config:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-config:verifyReleaseResources'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
```

My gradle settings:

```
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28
```

**Comment by sinodko** [comment]
you can try

```
dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
```

**Comment by Abramovick** [comment]
Also facing the same issue. @Flavien Any luck?

**Comment by santanapaulo** [comment]
Facing the same. Using version 0.57.1 react-native and 0.11.5 react-native-config.

**Comment by santanapaulo** [comment]
@Abramovick and @Flavien, I fixed my build process configuring my build.gradle like this: https://github.com/facebook/react-native/issues/19239#issuecomment-389939749

I guess it's a workaround, but it worked for me =)

**Comment by austincline09** [comment]
This fixed my problem. Try running it with 

`./gradlew app:assembleRelease`

**Comment by wswapped** [comment]
@austincline09 This was really helpful. Why does it work and what's the change? I appreciate

**Comment by ahtesham-shah** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

apk is building but when I changed version code and uploaded on play store its saying version code already exist means the version code not getting updated.

**Comment by arminghm** [comment]
any update on this?

**Comment by hao896259037** [comment]
@austincline09 Thank you very much! Solved my problem!

**Comment by stefanfrancis93** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

That worked. Thanks.🥇 💯

**Comment by Arizal-Arkan** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Thank you very much! 🥇 💯

**Comment by ym91** [comment]
Thanks! It helps!

**Comment by branvo** [comment]
Thanks. It Works

**Comment by michael-harley** [comment]
This is even worked for this case

`Execution failed for task ':react-native-background-task:verifyReleaseResources'.`

I think all `verifyReleaseResources` can be solved by adding app: in front of assembleRelease

Thanks!!

**Comment by ManalLiaquat** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Thanks! it worked.

**Comment by hindsricardo** [comment]
Why does this work?

**Comment by youngjuning** [comment]
Thanks for everyone

**Comment by Avishcar** [comment]
Thanks Brothers , You Are really Osm

**Comment by silverfh** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

super...

thats my bash .. and it worked puuuuufect


echo "Making Fresh Build"

rm android/app/src/main/assets/index.android.bundle
read -p "------> Bundle removed" -t 1

react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
read -p "------> Bundle created" -t 1

rm -r android/app/src/main/res/drawable-hdpi
rm -r android/app/src/main/res/drawable-mdpi
rm -r android/app/src/main/res/drawable-xhdpi
rm -r android/app/src/main/res/drawable-xxhdpi
rm -r android/app/src/main/res/drawable-xxxhdpi
read -p "------> drawable deleted" -t 1

cd ./android/ && ./gradlew clean && ./gradlew app:assembleRelease && cd ..
read -p "------> Build released" -t 1

**Comment by sutbult** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

This worked for me.

**Comment by nithinnaidu03** [comment]
> > This fixed my problem. Try running it with
> > `./gradlew app:assembleRelease`
> 
> apk is building but when I changed version code and uploaded on play store its saying version code already exist means the version code not getting updated.
Any solution found out for this ??

**Comment by thisWandiPratama** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

That worked. Thanks.1st_place_medal 100

**Comment by hmphu** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

That worked for me as well!!! Thank you so much

**Comment by juricablazevic** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

It wooorks!! Man, you saved my life!!! Thank you so so much for this solution!!! May God bless you!!!
I have wasted a whole one day just to build this!!! And you solved my problems! Respect man!

**Comment by FeMaffezzolli** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Perfect, works! But why?

**Comment by vognam** [comment]
This stackoverflow explains why it works:

https://stackoverflow.com/questions/60990805/difference-between-appassemblerelease-and-assemblerelease

**Comment by YangShaoXiong** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

thanks

**Comment by devararendy** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Mannn... it's works for me too. Greatttt Thank You so much

**Comment by jeffersonbritto** [comment]
Thank you!!!

> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

**Comment by Abddullah** [comment]
> > This fixed my problem. Try running it with
> > `./gradlew app:assembleRelease`
> 
> Thank you very much! 🥇 💯

thanks

**Comment by azytah** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

It's works! Thanks!

**Comment by MrVaibhav227** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

It's works! Thanks!

**Comment by kvntzn** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Still works, thanks !

**Comment by Samranvirk44** [comment]
./gradlew app:assembleRelease
this work fine for me

**Comment by prox2** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

you are a hero man, thanks

**Comment by nbaua** [comment]
I have a really wired issue here..

If I keep the delete the **assets/drawable-** folders and **raw** folder in the android ( of an react native app project) the **gradlew app:assembleRelease** and even **gradlew assembleRelease** commands work, however none of my icons appear for signed APK. 

If I do keep the above said folders nothing work when I am trying to generate the signed APK...
> Task :app:mergeReleaseResources FAILED
Lots of errors like .....

Duplicate resources
  [raw/node_modules_characterentitieslegacy_index] G:\MorenaBlues\app\android\app\build\generated\res\react\release\raw\node_modules_characterentitieslegacy_index.json 
  
[error-log.txt](https://github.com/luggit/react-native-config/files/6123337/error-log.txt)

This is something messing big time with me.. Please help.

**Comment by nbaua** [comment]
> I have a really wired issue here..
> 
> If I keep the delete the **assets/drawable-** folders and **raw** folder in the android ( of an react native app project) the **gradlew app:assembleRelease** and even **gradlew assembleRelease** commands work, however none of my icons appear for signed APK.
> 
> If I do keep the above said folders nothing work when I am trying to generate the signed APK...
> 
> > Task :app:mergeReleaseResources FAILED
> > Lots of errors like .....
> 
> Duplicate resources
> [raw/node_modules_characterentitieslegacy_index] G:\MorenaBlues\app\android\app\build\generated\res\react\release\raw\node_modules_characterentitieslegacy_index.json
> 
> [error-log.txt](https://github.com/luggit/react-native-config/files/6123337/error-log.txt)
> 
> This is something messing big time with me.. Please help.

I had to manually delete the raw and drawable-? folders

**Comment by prakashkrsingh0** [comment]
> > This fixed my problem. Try running it with
> > `./gradlew app:assembleRelease`
> 
> That worked. Thanks.🥇 💯



> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

It is working fine for me also. but Application size increased too much.

**Comment by reizhafajrian** [comment]
u need to clean your gradlew so i did it,./gradlew clean then npm run android that way work for me

**Comment by annamalaiselvam** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

worked! 👍🏻🎉

**Comment by dvlptuankiendo** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

I don't know why but it's worked. Thank you so much!

**Comment by Poxios** [comment]
> Why does this work?

Anyone?

**Comment by Lihao0510** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

love you, bro!

**Comment by netodomingos** [comment]
Worked!!! ❤️

**Comment by HasarBrasil** [comment]
@austincline09 Me ajudou aqui tbm. Obrigado!

**Comment by 49un9P** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

thanks bro!!!! 😎

**Comment by AmitHBhagat** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Thanks, it worked and built an apk for testing.

**Comment by bathiya96a** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Thank You! very very much! 
It worked for me too. I wonder why, does anybody know? how did it work? 

here's the issue that was fixed.
`Execution failed for task ':payhere_payhere-mobilesdk-reactnative:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed`

**Comment by qusyairin** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Worked! ✅

I had this issue

> 1: Task failed with an exception.
>-----------
>* What went wrong:
>Execution failed for task ':react-native-ssl-pinning:verifyReleaseResources'.

**Comment by GowthamResbee** [comment]
> This fixed my problem. Try running it with
> 
> `./gradlew app:assembleRelease`

Thank you so much man...!!!
