### ISSUE TITLE
Problems with v0.12.0 + React Native 0.61.4

### ISSUE THREAD

**Issue by c0d3x** [react-native-config/react-native-config#412]
Is there a migration guide from 0.11.7 to 0.12.0?
What do I need to remove from the old config, and what do I need to add to the new config?
**Do I need this config in the Podfile?**
```
    if target.name == 'react-native-config'
      phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
      phase.shell_script = "cd ../../"\
        " && RNC_ROOT=./node_modules/react-native-config/"\
        " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
        " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
        " && ruby $RNC_ROOT/ios/ReactNativeConfig/@BuildDotenvConfig.rb"

      target.build_phases << phase
      target.build_phases.move(phase,0)
    end
```

**I have added a config file in ios folder called Config.xcconfig with this line:**
#include? "tmp.xcconfig"

I get some build errors, when I try to upgrade from 0.11.7 to 0.12.0.

I have the following:
echo ".env.test" > /tmp/envfile
Added this line to it as the guide suggests:
![image](https://user-images.githubusercontent.com/661911/69436167-26033080-0d41-11ea-86f4-22a2e162b88b.png)

**I get this build error:**
/node_modules/react-native-config/ios/ReactNativeConfig/ReadDotEnv.rb:27:in `join': no implicit conversion of nil into String (TypeError)
	from /node_modules/react-native-config/ios/ReactNativeConfig/ReadDotEnv.rb:27:in `read_dot_env'
	from ./node_modules/react-native-config//ios/ReactNativeConfig/BuildDotenvConfig.rb:15:in `<main>'
reading env file from  and writing .m to 
going to read env file from root folder

**Comment by tgearig** [comment]
I have the same issue, and haven't been able to find a workaround.

**Comment by c0d3x** [comment]
Updates:
Removed the source script from the pre-actions on each env, and added it to a build phase:
![image](https://user-images.githubusercontent.com/661911/69548602-eb470580-0f97-11ea-9033-a3702842009a.png)

**Comment by c0d3x** [comment]
Now I cannot access env from Config object in iOS from React, works fine in Android though.

**Comment by jishuke** [comment]
I have the same issue, and haven't been able to find a workaround.

**Comment by phuoc-insignia** [comment]
+1

**Comment by el-lsan** [comment]
facing same issue.

**Comment by blackbing** [comment]
+1

**Comment by timkomip** [comment]
Not sure if this helps but...

We just upgraded to the latest and had to remove plist preprocessing (this is in Build Settings).
```
INFOPLIST_OTHER_PREPROCESSOR_FLAGS = "-traditional";
INFOPLIST_PREFIX_HEADER = "${BUILD_DIR}/GeneratedInfoPlistDotEnv.h";
INFOPLIST_PREPROCESS = YES
```

Also, we did **not** need to modify the Podfile with the script @c0d3x posted above.

**Comment by jitendralakhmani-proptiger** [comment]
Any update on this?

**Comment by hydraZty** [comment]
same issue

**Comment by hiepnm** [comment]
same issue

**Comment by sazanow** [comment]
same here

**Comment by shawnhong1** [comment]
Same issue

**Comment by zuhair-naqvi** [comment]
any updates?

**Comment by lisichka999** [comment]
Same here

**Comment by bradenpowers** [comment]
Seeing the same issue as well.  We have rolled back to 0.11.7

**Comment by twelve17** [comment]
I don't know if this will help, but I got some clarification to [my comment here](https://github.com/luggit/react-native-config/issues/413#issuecomment-577732479) (see the comments that follow it as well).  I am using v0.12.0 + RN 0.61.5.

**Comment by maxkomarychev** [comment]
hey 👋 I kindly ask to try my lib https://www.npmjs.com/package/react-native-ultimate-config if the issue persists. it works well for me in rn60+
